[colors]
background = #1e1e1e
background-alt = #2a2a2a
foreground = #eeeeec

primary = #3584e4
secondary = #78aeed
tertiary = #c0bfbc

green = #57e389
alert = #e01b24
disabled = #5e5c64

# Semantic colors
purple = #c061cb
yellow = #f6d32d
blue = #3584e4
pink = #ff6c6b
cyan = #5bc8af